spring:
  zipkin:
    baseUrl: http://zipkin.istio-system.svc:9411
    sender:
      type: web
  sleuth:
    opentracing:
      enabled: true
    baggage:
      correlation-enabled: true
      remote-fields: x-request-id
      correlation-fields: x-request-id

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState, livenessResponseCheck
        readiness:
          include: readinessState, db, kafka, webServices
    loggers:
      enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    webservices:
      readiness:
        services:
          - ${keycloak.url}

probes:
  liveness:
    failureThreshold: 10

data-platform:
  kafka:
    producer:
      enabled: true
    consumer:
      enabled: true
      group-id: user-settings-service-persistence
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      trusted-packages:
        - com.epam.digital.data.platform.model.core.kafka
        - com.epam.digital.data.platform.settings.model.dto
      error-handler:
        enabled-dlq: true
      custom-config:
        "[allow.auto.create.topics]": false
        "[retry.backoff.ms]": 10000
    topics:
      read-settings: read-settings-inbound
      update-settings: update-settings-inbound
