spring:
  zipkin:
    enabled: false

server:
  port: 8002

data-platform:
  datasource:
    url: jdbc:postgresql://localhost:5432/settings
    username: postgres
    password: qwerty
  kafka:
    bootstrap: ${KAFKA_BROKER:localhost:9092}
    ssl:
      enabled: false
  jwt:
    validation:
      enabled: false

management:
  endpoint:
    health:
      probes:
        enabled: true

# Not use for real token validation, just example
keycloak:
  url: https://platform-keycloak.apps.cicd2.mdtu-ddm.projects.epam.com
  realms:
    - realm

audit:
  kafka:
    bootstrap: localhost:9092
    topic: audit-events
    schema-registry-url: http://localhost:8081
    ssl:
      enabled: false
