spring:
  zipkin:
    baseUrl: http://zipkin.istio-system.svc:9411
    sender:
      type: web
  sleuth:
    opentracing:
      enabled: true
    baggage:
      correlation-enabled: true
      remote-fields: x-request-id
      correlation-fields: x-request-id

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState, livenessResponseCheck
        readiness:
          include: readinessState, kafka, db
    loggers:
      enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

probes:
  liveness:
    failureThreshold: 10

keycloak:
  url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}

data-platform:
  jwt:
    validation:
      enabled: false
  kafka:
    group-id: user-settings-service-persistence
    trusted-packages:
      - com.epam.digital.data.platform.model.core.kafka
      - com.epam.digital.data.platform.settings.model.dto
    error-handler:
      initial-interval: 1500
      max-elapsede-time: 6000
      multiplier: 2
    topics:
      read-settings: read-settings-inbound
      update-settings: update-settings-inbound
