spring:
  autoconfigure:
    exclude: com.epam.digital.data.platform.starter.database.DatabaseAutoConfiguration
  sql:
    init:
      mode: always

data-platform:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  signature:
    enabled: false
  kafka:
    bootstrap: localhost:9092
    topic-properties:
      num-partitions: 1
      replication-factor: 1
    ssl:
      enabled: false
audit:
  kafka:
    bootstrap: localhost:9092
    topic: audit-events
    schema-registry-url: http://localhost:8081
    ssl:
      enabled: false
keycloak:
  url: https://platform-keycloak.apps.cicd2.mdtu-ddm.projects.epam.com
  realms:
    - realm
