apiVersion: v1
kind: ConfigMap
metadata:
  name: user-settings-service-persistence-properties
data:
  config.yaml: |-
    data-platform:
      datasource:
        url: jdbc:postgresql://{{.Values.db.url}}:{{.Values.db.port}}/{{.Values.db.name}}
        connection-timeout: {{.Values.db.connectionTimeout}}
      kafka:
        bootstrap: {{ .Values.kafka.service }}
        ssl:
          enabled: {{ .Values.kafka.sslEnabled }}
      jwt:
        validation:
          enabled: true

    keycloak:
      url: {{ .Values.keycloak.host }}
      realms:
        - {{ .Values.ciProject }}-officer-portal
        - {{ .Values.ciProject }}-citizen-portal

    audit:
      kafka:
        bootstrap: {{ .Values.kafka.service }}
        topic: {{ .Values.audit.kafka.topic }}
        schema-registry-url: {{ .Values.audit.kafka.schemaRegistryUrl }}